spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: santiagoberriolopez@gmail.com
    password: kdrz olzv iyqz kkbx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: Notificaciones_db

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  port: 8085

